/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import fabrica.de.bebidas.FabricaBebidas;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author LukeSkywalker
 */
public class Economia extends javax.swing.JFrame {

    /**
     * Creates new form Empresa_1
     */
    FabricaBebidas fb = new FabricaBebidas();
    public Economia() {
        initComponents();
        try {
            fb.CargarProductos();
            fb.cargarCamiones();
            fb.CargarMaterias();
            
        } catch (IOException ex) {
            Logger.getLogger(Economia.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            fb.CargarTrabajadores();
        } catch (IOException ex) {
            Logger.getLogger(Economia.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextDineroAPagarTrabaja.setText(""+fb.CantidadDeDineroAPagarLaFabrica()+" Pesos");
        jTextCostoPro.setText(""+fb.VentaDeProductos()+" Pesos");
        String a =String.valueOf(fb.calcularCamiones());
        jTextDineroCamiones.setText(""+a+" Pesos");
        double d = fb.getCostoTotal();
        
        jTextCostoTotal.setText(""+(fb.VentaDeProductos()+124/2+110+fb.VentaDeProductos()/2.5)+""+" Pesos");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BorderLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextDineroAPagarTrabaja = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextDineroCamiones = new javax.swing.JTextField();
        jTextCostoPro = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextCostoTotal = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 560));

        BorderLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.add(BorderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 0, 0));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        jLabel6.setText("Economía de la empresa");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 270, 50));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Gadugi", 0, 36)); // NOI18N
        jLabel14.setText("Empresa de Bebidas");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 330, 60));

        jTextDineroAPagarTrabaja.setBackground(new java.awt.Color(204, 204, 204));
        jTextDineroAPagarTrabaja.setFont(new java.awt.Font("Gadugi", 0, 22)); // NOI18N
        jTextDineroAPagarTrabaja.setBorder(null);
        jPanel1.add(jTextDineroAPagarTrabaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 170, 30));

        jLabel28.setBackground(new java.awt.Color(0, 0, 0));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel28.setText("Dinero a Pagar a los Trabajadores:");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jLabel30.setBackground(new java.awt.Color(0, 0, 0));
        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel30.setText("Dinero gastado en Camiones:");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jTextDineroCamiones.setBackground(new java.awt.Color(204, 204, 204));
        jTextDineroCamiones.setFont(new java.awt.Font("Gadugi", 0, 22)); // NOI18N
        jTextDineroCamiones.setBorder(null);
        jPanel1.add(jTextDineroCamiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 170, 30));

        jTextCostoPro.setBackground(new java.awt.Color(204, 204, 204));
        jTextCostoPro.setFont(new java.awt.Font("Gadugi", 0, 22)); // NOI18N
        jTextCostoPro.setBorder(null);
        jPanel1.add(jTextCostoPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 170, 30));

        jLabel33.setBackground(new java.awt.Color(0, 0, 0));
        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel33.setText("Ingresos totales:");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, 30));

        jTextCostoTotal.setBackground(new java.awt.Color(204, 204, 204));
        jTextCostoTotal.setFont(new java.awt.Font("Gadugi", 0, 22)); // NOI18N
        jTextCostoTotal.setBorder(null);
        jTextCostoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCostoTotalActionPerformed(evt);
            }
        });
        jPanel1.add(jTextCostoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 170, 30));

        jLabel35.setBackground(new java.awt.Color(0, 0, 0));
        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel35.setText("Costo Total de Producción:");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        jButton3.setText("Atrás");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cloce.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        int xy, xx;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        xy = evt.getY();
        setOpacity((float) 0.8);
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
    setOpacity((float) 1);
    }//GEN-LAST:event_jPanel1MouseReleased

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Empresa_1 emp = new Empresa_1();
        emp.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Estás seguro de que deseas salir", "Salir", dialog);
        if (result == 0) {
            System.exit(0);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextCostoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCostoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCostoTotalActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BorderLabel;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextCostoPro;
    private javax.swing.JTextField jTextCostoTotal;
    private javax.swing.JTextField jTextDineroAPagarTrabaja;
    private javax.swing.JTextField jTextDineroCamiones;
    // End of variables declaration//GEN-END:variables
}
