package visual;

import fabrica.de.bebidas.FabricaBebidas;
import fabrica.de.bebidas.Exportacion;
import fabrica.de.bebidas.ConsumoNacional;
import fabrica.de.bebidas.MP_Importada;
import fabrica.de.bebidas.MP_Nacional;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Productos extends javax.swing.JFrame {
    
    DefaultTableModel md;
    DefaultTableModel mdo;
    String data[][] = {};
    String[] Nacional = {"Nombre", "FP", "FV", "Código", "Precio", "Cantidad", "Forma de Venta"};
    String[] Exportacion = {"Nombre", "FP", "FV", "Código", "Precio", "Cantidad", "Categoría"};
    
    FabricaBebidas fb = new FabricaBebidas();
    
    public Productos() {
        initComponents();
        int[] codigos;
        mImportadas.setSelected(true);
        mNacionales.setSelected(false);
        jLabel4.setText("Pais");
        jLabel4.setVisible(true);
        jTextField4.setVisible(true);
        mdo = new DefaultTableModel(data, Nacional);
        md = new DefaultTableModel(data, Exportacion);
        
        jTableProductosNacionales.setModel(mdo);
        jTableProductosExportacion.setModel(md);
        File fw = new File("Productos.txt");
        
        if (fw.exists() && fw.getTotalSpace() != 0) {
            try {
                fb.CargarProductos();
            } catch (IOException ex) {
                Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println("Cargando Datos");
//                System.out.println(fb.getProductos().get(0).getNombre());

            for (int i = 0; i < fb.getListaProductos().size(); i++) {
                
                if (fb.getListaProductos().get(i) instanceof ConsumoNacional) {
                    jComboBoxCodProd.addItem(((ConsumoNacional) fb.getListaProductos().get(i)).getCode());
                    String Nombre = ((ConsumoNacional) fb.getListaProductos().get(i)).getName();
                    String FechaVencimiento = ((ConsumoNacional) fb.getListaProductos().get(i)).getFechaV();
                    String FechaProducion = ((ConsumoNacional) fb.getListaProductos().get(i)).getFechaP();
                    String Codigo = ((ConsumoNacional) fb.getListaProductos().get(i)).getCode();
                    String Precio = ("" + ((ConsumoNacional) fb.getListaProductos().get(i)).getPrice() + "");
                    String Cantidad = ("" + ((ConsumoNacional) fb.getListaProductos().get(i)).getCantidad() + "");
                    String FormadeVenta = ((ConsumoNacional) fb.getListaProductos().get(i)).getSynisterGates();
                    String[] Nacinoal = {Nombre, FechaVencimiento, FechaProducion, Codigo, Precio, Cantidad, FormadeVenta};
                    mdo.addRow(Nacinoal);
                    System.out.println("Nacional");
                } else if (fb.getListaProductos().get(i) instanceof Exportacion) {
                    jComboBoxCodProd.addItem(((Exportacion) fb.getListaProductos().get(i)).getCode());
                    String Nombre = ((Exportacion) fb.getListaProductos().get(i)).getName();
                    String FechaVencimiento = ((Exportacion) fb.getListaProductos().get(i)).getFechaV();
                    String FechaProducion = ((Exportacion) fb.getListaProductos().get(i)).getFechaP();
                    String Codigo = ((Exportacion) fb.getListaProductos().get(i)).getCode();
                    String Precio = ("" + ((Exportacion) fb.getListaProductos().get(i)).getPrice() + "");
                    String Cantidad = ("" + ((Exportacion) fb.getListaProductos().get(i)).getCantidad() + "");
                    String Categoria = ("" + ((Exportacion) fb.getListaProductos().get(i)).getCategoria() + "");
                    String[] Exportacion = {Nombre, FechaVencimiento, FechaProducion, Codigo, Precio, Cantidad, Categoria};
                    md.addRow(Exportacion);
                    System.out.println("Exporta");
                }
                
            }
        }
        try {
            fb.CargarMaterias();
        } catch (IOException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextFechaPNacional = new javax.swing.JTextField();
        jTextCodigoNacional = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextNombreNacional = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFechaVNacional = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextPrecioNacional = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jTextCantidadNacional = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextFormaVentaNacional = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableProductosExportacion = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableProductosNacionales = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jComboBoxCodProd = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        codigo = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        mNacionales = new javax.swing.JRadioButton();
        mImportadas = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jTextFechaPExportacion = new javax.swing.JTextField();
        jTextCodigoExportacion = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextNombreExporta = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextFechaVExportacion = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextPrecioExportacion = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jTextCantidadExportacion = new javax.swing.JTextField();
        jComboCategoriaExportacion = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 560));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel14.setText("Añadir Productos:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 290, 40));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("FechaP:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jTextFechaPNacional.setFont(new java.awt.Font("Gadugi", 0, 22)); // NOI18N
        jTextFechaPNacional.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFechaPNacional.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFechaPNacionalKeyTyped(evt);
            }
        });
        jPanel3.add(jTextFechaPNacional, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 190, 30));

        jTextCodigoNacional.setFont(new java.awt.Font("Gadugi", 0, 22)); // NOI18N
        jTextCodigoNacional.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextCodigoNacional.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCodigoNacionalKeyTyped(evt);
            }
        });
        jPanel3.add(jTextCodigoNacional, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 190, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Código:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        jTextNombreNacional.setFont(new java.awt.Font("Gadugi", 0, 22)); // NOI18N
        jTextNombreNacional.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextNombreNacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreNacionalActionPerformed(evt);
            }
        });
        jTextNombreNacional.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNombreNacionalKeyTyped(evt);
            }
        });
        jPanel3.add(jTextNombreNacional, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 190, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Nombre:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jTextFechaVNacional.setFont(new java.awt.Font("Gadugi", 0, 22)); // NOI18N
        jTextFechaVNacional.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFechaVNacional.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFechaVNacionalKeyTyped(evt);
            }
        });
        jPanel3.add(jTextFechaVNacional, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 190, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("FechaV:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jTextPrecioNacional.setFont(new java.awt.Font("Gadugi", 0, 22)); // NOI18N
        jTextPrecioNacional.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextPrecioNacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPrecioNacionalActionPerformed(evt);
            }
        });
        jTextPrecioNacional.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPrecioNacionalKeyTyped(evt);
            }
        });
        jPanel3.add(jTextPrecioNacional, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 190, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Precio:");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jButton1.setText("Agregar");
        jButton1.setToolTipText("");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 110, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Cantidad:");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        jTextCantidadNacional.setFont(new java.awt.Font("Gadugi", 0, 22)); // NOI18N
        jTextCantidadNacional.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextCantidadNacional.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextCantidadNacionalKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCantidadNacionalKeyTyped(evt);
            }
        });
        jPanel3.add(jTextCantidadNacional, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 190, 30));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("Forma de Venta:");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 140, -1));

        jTextFormaVentaNacional.setFont(new java.awt.Font("Gadugi", 0, 22)); // NOI18N
        jTextFormaVentaNacional.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFormaVentaNacional.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFormaVentaNacionalKeyTyped(evt);
            }
        });
        jPanel3.add(jTextFormaVentaNacional, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 190, 30));

        jTabbedPane1.addTab("Consumo Nacional", jPanel3);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableProductosExportacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableProductosExportacion);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 130));

        jTableProductosNacionales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTableProductosNacionales);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 130));

        jLabel3.setText("Productos Exportados");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jLabel5.setText("Consumo Nacional");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jButton7.setText("Actualizar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, 30));

        jTabbedPane1.addTab("Productos", jPanel4);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxCodProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCodProdActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBoxCodProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 70, -1));

        jLabel2.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel2.setText("Código:");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, 30));

        nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreKeyTyped(evt);
            }
        });
        jPanel5.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 90, -1));

        codigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoActionPerformed(evt);
            }
        });
        codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigoKeyTyped(evt);
            }
        });
        jPanel5.add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 80, -1));

        precio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioActionPerformed(evt);
            }
        });
        precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                precioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                precioKeyTyped(evt);
            }
        });
        jPanel5.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 70, -1));

        mNacionales.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(mNacionales);
        mNacionales.setFont(new java.awt.Font("Gadugi", 2, 14)); // NOI18N
        mNacionales.setText("Nacionales");
        mNacionales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNacionalesActionPerformed(evt);
            }
        });
        jPanel5.add(mNacionales, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        mImportadas.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(mImportadas);
        mImportadas.setFont(new java.awt.Font("Gadugi", 2, 14)); // NOI18N
        mImportadas.setText("Importadas");
        mImportadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mImportadasActionPerformed(evt);
            }
        });
        jPanel5.add(mImportadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel4.setText("Var");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, 50));

        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 80, -1));

        jButton4.setText("Añadir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        jLabel37.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel37.setText("Tipo de Materia Prima:");
        jPanel5.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, 30));

        jLabel38.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel38.setText("Nombre:");
        jPanel5.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, 30));

        jLabel39.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel39.setText("Precio:");
        jPanel5.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, 30));

        jLabel40.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel40.setText("Código Producto:");
        jPanel5.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, 30));

        jTabbedPane1.addTab("Materia Prima", jPanel5);

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setText("FechaP:");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        jTextFechaPExportacion.setFont(new java.awt.Font("Gadugi", 0, 22)); // NOI18N
        jTextFechaPExportacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFechaPExportacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFechaPExportacionKeyTyped(evt);
            }
        });
        jPanel6.add(jTextFechaPExportacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 190, 30));

        jTextCodigoExportacion.setFont(new java.awt.Font("Gadugi", 0, 22)); // NOI18N
        jTextCodigoExportacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextCodigoExportacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCodigoExportacionKeyTyped(evt);
            }
        });
        jPanel6.add(jTextCodigoExportacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 190, 30));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setText("Código:");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        jTextNombreExporta.setFont(new java.awt.Font("Gadugi", 0, 22)); // NOI18N
        jTextNombreExporta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextNombreExporta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNombreExportaKeyTyped(evt);
            }
        });
        jPanel6.add(jTextNombreExporta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 190, 30));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel28.setText("Nombre:");
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jTextFechaVExportacion.setFont(new java.awt.Font("Gadugi", 0, 22)); // NOI18N
        jTextFechaVExportacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFechaVExportacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFechaVExportacionKeyTyped(evt);
            }
        });
        jPanel6.add(jTextFechaVExportacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 190, 30));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel30.setText("FechaV:");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jTextPrecioExportacion.setFont(new java.awt.Font("Gadugi", 0, 22)); // NOI18N
        jTextPrecioExportacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextPrecioExportacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPrecioExportacionKeyTyped(evt);
            }
        });
        jPanel6.add(jTextPrecioExportacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 190, 30));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel33.setText("Precio:");
        jPanel6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        jButton2.setText("Agregar");
        jButton2.setToolTipText("");
        jButton2.setBorder(new javax.swing.border.MatteBorder(null));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 110, 30));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel34.setText("Categoría:");
        jPanel6.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, 50));

        jTextCantidadExportacion.setFont(new java.awt.Font("Gadugi", 0, 22)); // NOI18N
        jTextCantidadExportacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextCantidadExportacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCantidadExportacionKeyTyped(evt);
            }
        });
        jPanel6.add(jTextCantidadExportacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 190, 30));

        jComboCategoriaExportacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel6.add(jComboCategoriaExportacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 190, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel36.setText("Cantidad:");
        jPanel6.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        jTabbedPane1.addTab("Exportación", jPanel6);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 510, 440));

        jButton3.setText("Atrás");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cloce.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 30, 30));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cloce.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 20, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        int xy, xx;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        xy = evt.getY();
        setOpacity((float) 0.8);
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        setOpacity((float) 1);
    }//GEN-LAST:event_jPanel1MouseReleased

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        

    }//GEN-LAST:event_jButton2MouseClicked

    private void jComboBoxCodProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCodProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCodProdActionPerformed

    private void nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyTyped
        char typed = evt.getKeyChar();
        if ((typed == ',')|| jTextNombreNacional.getText().length() > 99) {
            evt.consume();
        }// TODO add your handling code here:

    }//GEN-LAST:event_nombreKeyTyped

    private void precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioActionPerformed

    private void precioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(c >= '0' && c <= '9')) {
            if (c == '.') {
                
            } else {
                evt.consume();
            }
        }
    }//GEN-LAST:event_precioKeyTyped

    private void precioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_precioKeyReleased

    private void mNacionalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNacionalesActionPerformed
        // TODO add your handling code here:
        if (mNacionales.isSelected()) {
            mImportadas.setSelected(false);
            jLabel4.setText("Empresa");
            jLabel4.setVisible(true);
            jTextField4.setVisible(true);
        } else {
            jLabel4.setVisible(false);
            jTextField4.setVisible(false);
        }
    }//GEN-LAST:event_mNacionalesActionPerformed

    private void mImportadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mImportadasActionPerformed
        // TODO add your handling code here:
        if (mImportadas.isSelected()) {
            mNacionales.setSelected(false);
            jLabel4.setText("Pais");
            jLabel4.setVisible(true);
            jTextField4.setVisible(true);
        } else {
            jLabel4.setVisible(false);
            jTextField4.setVisible(false);
        }
    }//GEN-LAST:event_mImportadasActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            fb.CargarMaterias();
        } catch (IOException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (!jComboBoxCodProd.getSelectedItem().toString().equals("")) {
            if (!nombre.getText().equals("") && !codigo.getText().equals("") && !precio.getText().equals("")) {
                if (mNacionales.isSelected()) {
                    if (!jTextField4.getText().equals("")) {
                        MP_Nacional nueva = new MP_Nacional(jTextField4.getText(), nombre.getText(), codigo.getText(), Double.valueOf(precio.getText()));
                        fb.AddMateriaPrimaDadoProducto(jComboBoxCodProd.getSelectedItem().toString(), nueva);
                        JOptionPane.showMessageDialog(rootPane, "Se a añadido correctamente la Materia Prima");
                        
            nombre.setText("");
            codigo.setText("");
            precio.setText("");
            jTextField4.setText("");
            
                        try {
                            fb.GuardarListMateriales(jComboBoxCodProd.getSelectedItem().toString(), nueva);
                        } catch (IOException ex) {
                            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        nombre.setText("");
                        codigo.setText("");
                        precio.setText("");
                        jTextField4.setText("");
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Faltan parametros por llenar");
                    }
                    
                } else {
                    if (mImportadas.isSelected()) {
                        if (!jTextField4.getText().equals("")) {
                            MP_Importada nueva = new MP_Importada(jTextField4.getText(), nombre.getText(), codigo.getText(), Double.valueOf(precio.getText()));
                            fb.AddMateriaPrimaDadoProducto(jComboBoxCodProd.getSelectedItem().toString(), nueva);
                            try {
                                fb.GuardarListMateriales(jComboBoxCodProd.getSelectedItem().toString(), nueva);
                            } catch (IOException ex) {
                                Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            
                            JOptionPane.showMessageDialog(rootPane, "Se a añadido correctamente la Materia Prima");
                            nombre.setText("");
                            codigo.setText("");
                            precio.setText("");
                            jTextField4.setText("");
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Faltan parametros por llenar");
                        }
                        
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Selecciona el tipo de Materia Prima");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Faltan parametros por llenar");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Seleccione el codigo del producto al que pertenece la Materia Prima");
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextNombreExportaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNombreExportaKeyTyped
        // TODO add your handling code here:        char c = evt.getKeyChar();
        char typed = evt.getKeyChar();
        if ((typed == ',')|| jTextNombreNacional.getText().length() > 99) {
            evt.consume();
            
        }
    }//GEN-LAST:event_jTextNombreExportaKeyTyped

    private void jTextCantidadExportacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCantidadExportacionKeyTyped
        char c = evt.getKeyChar();
        if (c >= '0' && c <= '9') {
        } else {
            evt.consume();
            
        }
    }//GEN-LAST:event_jTextCantidadExportacionKeyTyped

    private void jTextNombreNacionalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNombreNacionalKeyTyped
        char typed = evt.getKeyChar();
        if ((typed == ',')|| jTextNombreNacional.getText().length() > 99) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextNombreNacionalKeyTyped

    private void jTextCantidadNacionalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCantidadNacionalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCantidadNacionalKeyPressed

    private void jTextCantidadNacionalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCantidadNacionalKeyTyped
        char c = evt.getKeyChar();
        if (c >= '0' && c <= '9') {
        } else {
            evt.consume();
            
        }
    }//GEN-LAST:event_jTextCantidadNacionalKeyTyped

    private void jTextFormaVentaNacionalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFormaVentaNacionalKeyTyped
        char c = evt.getKeyChar();
        if (!(c >= '0' && c <= '9')) {
        } else {
            evt.consume();
            
        }
    }//GEN-LAST:event_jTextFormaVentaNacionalKeyTyped

    private void jTextCodigoExportacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCodigoExportacionKeyTyped
        char typed = evt.getKeyChar();
        if (!(typed >= '0' && typed <= '9') || jTextCodigoNacional.getText().length() > 10) {
            evt.consume();        // TODO add your handling code here:
        }                  // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigoExportacionKeyTyped

    private void jTextPrecioExportacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPrecioExportacionKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c >= '0' && c <= '9') || (c == '.')) {
            
        } else {
            evt.consume();
            
        }
    }//GEN-LAST:event_jTextPrecioExportacionKeyTyped

    private void jTextPrecioNacionalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPrecioNacionalKeyTyped
        char c = evt.getKeyChar();
        if (!(c >= '0' && c <= '9')) {
            if ((c == '.')) {
            } else {
                evt.consume();
                
            }
        }
    }//GEN-LAST:event_jTextPrecioNacionalKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Empresa_1 emp = new Empresa_1();
        emp.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Estás seguro de que deseas salir", "Salir", dialog);
        if (result == 0) {
            System.exit(0);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Estás seguro de que deseas salir", "Salir", dialog);
        if (result == 0) {
            System.exit(0);
        }      // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextNombreNacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreNacionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreNacionalActionPerformed

    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoActionPerformed

    private void codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoKeyTyped
        char typed = evt.getKeyChar();
        if (!(typed >= '0' && typed <= '9') || codigo.getText().length() > 10) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_codigoKeyTyped

    private void jTextFechaPExportacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFechaPExportacionKeyTyped
        char typed = evt.getKeyChar();
        if (!(typed >= '0' && typed <= '9') || jTextFechaPExportacion.getText().length() > 10) {
            if (!(typed == '/')) {
                if (!(typed == '-')) {
                    evt.consume();
                }
            }
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jTextFechaPExportacionKeyTyped

    private void jTextFechaVNacionalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFechaVNacionalKeyTyped
        char typed = evt.getKeyChar();
        if (!(typed >= '0' && typed <= '9') || jTextFechaVNacional.getText().length() > 10) {
            if (!(typed == '/')) {
                if (!(typed == '-')) {
                    evt.consume();
                }
            }
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jTextFechaVNacionalKeyTyped

    private void jTextFechaPNacionalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFechaPNacionalKeyTyped
        char typed = evt.getKeyChar();
        if (!(typed >= '0' && typed <= '9') || jTextFechaPNacional.getText().length() > 10) {
            if (!(typed == '/')) {
                if (!(typed == '-')) {
                    evt.consume();
                }
            }
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jTextFechaPNacionalKeyTyped

    private void jTextCodigoNacionalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCodigoNacionalKeyTyped
        char typed = evt.getKeyChar();
        if (!(typed >= '0' && typed <= '9') || jTextCodigoNacional.getText().length() > 10) {
            evt.consume();
        }     // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigoNacionalKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String a = jTextNombreNacional.getText();
        String b = jTextFechaVNacional.getText();
        String c = jTextFechaPNacional.getText();
        String d = jTextFormaVentaNacional.getText();
        String e = jTextCodigoNacional.getText();
        
        if (!a.equals("") && !b.equals("") && !c.equals("") && !d.equals("")
                && !e.equals("") && (!(jTextCantidadNacional.getText().equals("")))
                && (!(jTextPrecioNacional.getText().equals("")))) {
            int Cantidad = Integer.parseInt(jTextCantidadNacional.getText());
            double Precio = Double.parseDouble(jTextPrecioNacional.getText());
            //String formaVenta, String nombre, String FechaVencimiento, String FechaProduccion, double precio, int Cantidad
            fb.AddProducto(new ConsumoNacional(d, a, b, c, e, Precio, Cantidad));
            System.out.println("Producto Nacional Añadido Correctamente");
            try {
                fb.GuardarListProductos();
            } catch (IOException ex) {
                Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            jTextNombreNacional.setText("");
            jTextFechaVNacional.setText("");
            jTextFechaPNacional.setText("");
            jTextCodigoNacional.setText("");
            jTextPrecioNacional.setText("");
            jTextCantidadNacional.setText("");
            jTextFormaVentaNacional.setText("");
            JOptionPane.showMessageDialog(rootPane, "Producto añadido correctamente");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Faltan campos por llenar");
        } // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String a = jTextNombreExporta.getText();
        String b = jTextFechaVExportacion.getText();
        String c = jTextFechaPExportacion.getText();
        String d = jComboCategoriaExportacion.getSelectedItem().toString();
        String f = jTextCodigoExportacion.getText();
        if (!a.equals("") && !b.equals("") && !c.equals("") && (!(jTextPrecioExportacion.getText().equals(""))) && !f.equals("") && (!(jTextPrecioExportacion.getText().equals(""))) && (!(jTextCantidadExportacion.getText().equals("")))) {
            double e = Double.parseDouble(jTextPrecioExportacion.getText());
            int Cantidad = Integer.parseInt(jTextCantidadExportacion.getText());
            //String formaVenta, String nombre, String FechaVencimiento, String FechaProduccion, double precio, int Cantidad
            fb.AddProducto(new Exportacion(d, a, b, c, f, e, Cantidad));
            System.out.println("Producto Exportación Añadido Correctamente");
            try {
                fb.GuardarListProductos();
            } catch (IOException ex) {
                Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            jTextNombreExporta.setText("");
            jTextFechaVExportacion.setText("");
            jTextFechaPExportacion.setText("");
            jTextCodigoExportacion.setText("");
            jTextPrecioExportacion.setText("");
            jTextCantidadExportacion.setText("");
            JOptionPane.showMessageDialog(rootPane, "Producto añadido correctamente");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Faltan datos por llenar");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextPrecioNacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPrecioNacionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPrecioNacionalActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            fb.GuardarListProductos();
        } catch (IOException ex) {
            Logger.getLogger(Trabajadores.class.getName()).log(Level.SEVERE, null, ex);
        }
        Productos t1c = new Productos();
        t1c.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextFechaVExportacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFechaVExportacionKeyTyped
        char typed = evt.getKeyChar();
        if (!(typed >= '0' && typed <= '9') || jTextFechaVNacional.getText().length() > 10) {
            if (!(typed == '/')) {
                if (!(typed == '-')) {
                    evt.consume();
                }
            }
        }            // TODO add your handling code here:
    }//GEN-LAST:event_jTextFechaVExportacionKeyTyped

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField codigo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBoxCodProd;
    private javax.swing.JComboBox<String> jComboCategoriaExportacion;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableProductosExportacion;
    private javax.swing.JTable jTableProductosNacionales;
    private javax.swing.JTextField jTextCantidadExportacion;
    private javax.swing.JTextField jTextCantidadNacional;
    private javax.swing.JTextField jTextCodigoExportacion;
    private javax.swing.JTextField jTextCodigoNacional;
    private javax.swing.JTextField jTextFechaPExportacion;
    private javax.swing.JTextField jTextFechaPNacional;
    private javax.swing.JTextField jTextFechaVExportacion;
    private javax.swing.JTextField jTextFechaVNacional;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextFormaVentaNacional;
    private javax.swing.JTextField jTextNombreExporta;
    private javax.swing.JTextField jTextNombreNacional;
    private javax.swing.JTextField jTextPrecioExportacion;
    private javax.swing.JTextField jTextPrecioNacional;
    private javax.swing.JRadioButton mImportadas;
    private javax.swing.JRadioButton mNacionales;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField precio;
    // End of variables declaration//GEN-END:variables
}
